sonar.projectKey=apmantza_pi-webaio
sonar.organization=apmantza
sonar.sources=.
sonar.exclusions=tests/**/*,node_modules/**/*
sonar.cpd.exclusions=tests/**/*
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
